### ISSUE TITLE
Add rdfs:label for all classes and properties

### ISSUE THREAD

**Issue by gatemezing** [OntoUML/ontouml-schema-owl#10]
Hello all,
Great work. See the URL in LOV at https://lov.linkeddata.es/dataset/lov/vocabs/ontouml. However, it is important to add annotations (at least labels) for ease reuse of the terms, and search. See also [this check list](https://www.w3.org/TR/ld-bp/#vocabulary-checklist)

**Comment by pedropaulofb** [comment]
@gatemezing, thank you for your concern and for the valuable reference. 

We significantly improved the vocabulary's data and metadata to its [newest version to be soon released](https://github.com/OntoUML/ontouml-vocabulary/pull/9). This new version contains labels to all the vocabulary entities.

**Comment by pedropaulofb** [comment]
[Version 1.1.0](https://github.com/OntoUML/ontouml-vocabulary/releases/tag/v1.1.0) released.
